import os
import re
from uuid import UUID
from fastapi import HTTPException

def validate_uuid(uuid_string: str) -> bool:
    """Validate that a string is a valid UUID."""
    try:
        val = UUID(uuid_string, version=4)
        return str(val) == uuid_string
    except ValueError:
        return False

def validate_safe_filename(filename: str) -> str:
    """
    Validate that a filename is safe to use.
    - No path separators
    - No .. or .
    - Allowed characters only
    """
    # Prevent path traversal
    if ".." in filename or "/" in filename or "\\" in filename:
        raise HTTPException(status_code=400, detail="Invalid filename")

    # Check for null bytes
    if "\0" in filename:
        raise HTTPException(status_code=400, detail="Invalid filename")

    return filename

def validate_file_id(file_id: str) -> str:
    """Validate that file_id is a valid UUID or safe identifier."""
    # For now, we enforce UUID format for file_ids generated by the system
    # But some might be safe alphanumeric strings if needed
    if not validate_uuid(file_id):
        # If strict UUID not required, at least check for safety
        if not re.match(r"^[a-zA-Z0-9_-]+$", file_id):
             raise HTTPException(status_code=400, detail="Invalid file ID format")
    return file_id
